### ISSUE TITLE
Cache Content value of message

### ISSUE THREAD

**Issue by gunr2171** [ArcticEcho/ChatExchange.Net#10]
<sub>Today I learned...</sub>

The `Content` property looks like this:

```
public string Content
{
    get
    {
        return GetMessageContent(Host, ID, stripMention);
    }
}
```

This really threw me for a loop. I didn't ever look, but I had no idea that every time I accessed a message's content it would do an internet lookup.

> And that wouldn't be to bad unless you use it in a loop to check for the possible actions  
> Which make you call GET /message/22303213?plain=true HTTP/1.1 **25** times in succession
[rene's messages](http://chat.stackoverflow.com/transcript/message/22303217#22303217)

So....I would like this to change. The easy thing I can think of is to store the value once it has been accessed the first time, and return the stored value again if requested.

```
private string _content = null;
public string Content
{
    get
    {
        if (_content != null) return _content;
        _content = GetMessageContent(Host, ID, stripMention);
        return _content;
    }
}
```
<sub>This is a quick sketch up</sub>

Now, of course. We should decide if this makes logical sense. Should the end-user be responsible for caching the value or should the library?

For more reading, see [rene's discovery of this problem in the testing chat room](http://chat.stackoverflow.com/transcript/message/22303202#22303202).

**Comment by gunr2171** [comment]
Another option: cache all the values (like `StarCount` and `PinCount`), and provide a single method to "refresh" all the values.

    public void RefreshAllValues()

This way you could have all cached values until you explicitly say to fetch new data.

**Comment by ArcticEcho** [comment]
Ideally the library itself should handle all caching. For the `Content` property, I'll just hook up the `MessageEditedEventHandler`, check if the necessary values (don't) match and then invalidate. As for the start/pin count, as you suggested, cache invalidatation will be handled manually (i.e., only when the user says).
