### ISSUE TITLE
Create nuget releases for this library

### ISSUE THREAD

**Issue by gunr2171** [ArcticEcho/ChatExchange.Net#11]
This is a formal write-up for the nuget project we've talked about in chat. 

To recap:

Visual studio is giving us a hard time with project references and nuget packages mixed with submodules. We've had to resort to including the nuget packages directly in the repository so we can keep using the submodules. We don't like that one bit.

Instead, let's ditch submodules for exclusively nuget packages. We don't _need_ submodules; those are only good if you want to develop the inner repo along with the outer one. For the CV chat bot (or others) we don't need to do that. All we want is to consume and use the library.

This is where nuget come in. It's designed to be a packaging system where other developers can use your libraries with minimal hassle. No committing binaries to repo, no referencing source code.

---

The good news is that packaging in nuget is very straight forward. All you do is configure one or two xml config files, drop in your binaries into a folder, run a command, and you're done.

This is how I make nuget packages for [TCL](https://www.nuget.org/packages/TCL.Extensions). 

There is a [VS extension](https://visualstudiogallery.msdn.microsoft.com/daf5c6db-386b-4994-bdd7-b6cd52f11b72) that let's you create a new template project all set up for nuget packaging. All that needs to be done is:

* Edit the `nuspec` and `nuget.config` files to your liking. The `nuspec` hold metadata about the project (name, description, dependencies, etc), and the `nuget.config` file tells where you want to publish to (nuget.org, local file system, etc).
* Make some post-build events on your main project to copy over the needed dll (remember to not copy over "dependency" dlls)
* Build the publisher project in Debug mode to create a nuget package in the project director, or build in Release mode to also publish the package to your specified targets.

There is one downside to this approach. You need to manually change the version number each time you want to publish a new package. If you're only doing this once and a while it's ok, but anything more is a pain.

I use Jenkins to do that for me. Jenkins checks out out a specific commit of the code base, fixes all the config files (including inserting a new version number), then compiles and publishes, all in a single job. It makes my life super-easy. I don't know if Travis CI can do something like this, but if it can it might be worth it to set up.

I've already done some work on getting CE.Net nuget-able using the above method, and it's in [my fork's "nuget" branch](https://github.com/ArcticEcho/ChatExchange.Net/compare/ArcticEcho:master...gunr2171:nuget?expand=1). I'll finish it up and PR it once we decide if we like it or not.

**Comment by ArcticEcho** [comment]
All [done](https://www.nuget.org/packages/ChatExchange.Net/).
