### ISSUE TITLE
Make ChatExchange.Net compatiable with Mono and Linux

### ISSUE THREAD

**Issue by gunr2171** [ArcticEcho/ChatExchange.Net#12]
Getting this library to work in Linux with Mono would open up the door for other developers with cross-platform compatibility.

I know I would like this: it's much easier to run a bot 24/7 on Linux than Windows.

**Comment by gunr2171** [comment]
According to tests roughly a week or 2 ago, we determined that the library could post message to chat, but not recieve anything. We believe it is due to websockets.

**Comment by ArcticEcho** [comment]
I'll created a new branch ([mono-compatible](https://github.com/ArcticEcho/ChatExchange.Net/tree/mono-compatible/ChatExchange.Net)) that should solve this issue.
