### ISSUE TITLE
Display pings in messages.

### ISSUE THREAD

**Issue by ardaozkal** [ArcticEcho/ChatExchange.Net#19]
When I ping someone, I can't see the ping part of the message.

For ex. "hello @ardaozkal I'm new here" shows up as "hello I'm new here".

Version: 3.4.0.1 from Nuget

**Comment by ArcticEcho** [comment]
Ah, yes. This is the [defualt](https://github.com/ArcticEcho/ChatExchange.Net/blob/master/ChatExchange.Net/Room.cs#L72) behaviour of the Room class. You can disable this feature by setting `.StripMention` to `false`.

Admittedly I shouldn't have set this to `true` by default. I'll release a patch for this in the next build.

**Comment by ardaozkal** [comment]
You are _way_ too fast. I just found the workaround, I'll just use this 

> Message.GetMessageContent(message.Host, message.ID, false);

**Comment by ArcticEcho** [comment]
Lol. Well, just be warned, calling that method will fetch the message's latest content (via another GET req).
