### ISSUE TITLE
Not able to join room because GetMe function can't parse "meta.stackexchange.com" as an integer

### ISSUE THREAD

**Issue by gunr2171** [ArcticEcho/ChatExchange.Net#5]
I'm trying to run the build-in example.

There is a `GetMe()` function on line 552. I get the following exception on line 562:

    var id = int.Parse(e.Attributes["href"].Split('/')[2]);

>An unhandled exception of type 'System.FormatException' occurred in mscorlib.dll

> Input string was not in a correct format.

This is the value of `e.Attributes["href"]`

<pre>
http://meta.stackexchange.com/users/login?returnurl=http%3a%2f%2fchat.meta.stackexchange.com%2fchats%2fjoin%2ffavorite
</pre>

And this is the value after the `.Split('/')`.

    [0] "http:"
    [1] ""
    [2] "meta.stackexchange.com"  <-- obviously this is not an int
    [3] "users"
    [4] "login?returnurl=http%3a%2f%2fchat.meta.stackexchange.com%2fchats%2fjoin%2ffavorite"

From what I can gather about this, the site is not logging in correctly. 

I tried this with my main account as well as a [brand new account](http://meta.stackexchange.com/users/278477/gunr2171s-bot) that only has a stack exchange open Id (my main account has Google as well).

So, what do I need to do to get an account working?

**Comment by ArcticEcho** [comment]
Can you set a breakpoint at line 126 in `Client.cs`, and then post the value of `url`. Thanks.

**Comment by gunr2171** [comment]
This is the value of `url`:

    https://openid.stackexchange.com/account/prompt?session=04600b82-4126-4c11-8753-72a3e96c69f8

I also looked at the value of `data` below it, and saw this:

    session=<input type="hidden" name="session" value="04600b82-4126-4c11-8753-72a3e96c69f8" />&fkey=0d4d4f37-d0a2-45fb-8752-c222653d7be2

I'm not sure if that is intentional or not, but it seems to be putting in the html of the input element into the string.
